version: '3'

services:
  app:
    image: node:12.16-alpine
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
      - 3333:3333
    stdin_open: true
    command: sh -c "yarn && (yarn run start-json-server & yarn start)"
